import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import ToastProvider from "@/providers/ToastProvider";
import Image from "next/image";
import Background from "@/public/assets/BackgroundImage.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "URL Shorter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Image
          alt="Background"
          src={Background}
          layout="fill"
          objectFit="cover"
          quality={100}
        /> */}
        <ToastProvider />
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
